export default {
  //
  AUTHENTICATION_STACK: 'AUTHENTICATION_STACK',
  APP_TAB: 'APP_TAB',
  //
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  //
  CONVERSATION_SCREEN: 'CONVERSATION_SCREEN',
  USERS_SCREEN: 'USERS_SCREEN',
};
