export default {
  //
  AUTHENTICATION_STACK: 'AUTHENTICATION_STACK',
  APP_TAB: 'APP_TAB',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  //
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  //

  CONVERSATION_STACK: 'CONVERSATION_STACK',
  //
  CONVERSATION_SCREEN: 'CONVERSATION_SCREEN',
  USERS_SCREEN: 'USERS_SCREEN',
  CHAT_SCREEN: 'CHAT_SCREEN',
};
